config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :venues do
    member do
      patch :favorite
      get :confirm
      get :success
    end
    resources :bookings, only: %i[new create]


  end

  resources :bookings, only: %i[show edit update destroy] do
    resources :reviews,  only: %i[new create edit update]
  end

  get "read", to: "pages#read"
  get "/dashboard", to: "pages#dashboard"
  get "/activity", to: "pages#activity"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form_booking.html.erb
<div class="input-container">
  <%= simple_form_for [venue, booking] do |f| %>
    <%= f.input :booking_date,
      as: :integer, label: false,
      input_html: {  placeholder: "e.g. Today", data: { controller: "datepicker" }, class:"input-bf" } %>
    <%# <label class="placeholder" for="venue_booking_booking_date" style="background-color: white; color: #48484a">heyhey</label> %>
    <div style="padding-top: 20px">
      <h3>Reservation Request Overview:</h3>
      <p>1 seat at <%= venue.name %>.</p>
    </div>
    <div style="padding-top: 40px">
      <%= button_tag type: 'submit', class: "btn btn-primary" do %>
        <i class="bi-calendar-plus"></i> Reserve now
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_form_review.html.erb
<%= simple_form_for [booking, review] do |f| %>
  <h3 style="font-size: 17px;">Give a star rating...</h3>
    <%= f.input :rating, collection: (1..5).to_a, label: false, prompt: false, input_html: {data: {controller: "star-rating"}}%>
  <h3 style="font-size: 17px;">Write your review...</h3>
  <%= f.input :content, label: false, placeholder: "Type something..." %>
  <h3 style="font-size: 17px;">Add pictures (optional)</h3>
  <span><img class="preview-blob d-none" data-preview-target="preview"></img></span>
  <div data-preview-target="tagwrapper">
    <%= f.input :photos, as: :file,
    input_html: {
      multiple: true,
      class: "tag-selector",
      data: {
        action: "change->preview#readURLS"
        }},
      label: "+",
      wrapper_html: {
        class: "tag-item"
        },
        prompt: "" %>
  </div>
    <div>
      <%= button_tag type: 'submit', class: "btn btn-primary" do %>
        <i class="bi bi-chat-square-text"></i> Save review
      <% end %>
    </div>

<% end %>

app/views/shared/_form_venue.html.erb
<%= simple_form_for(venue) do |f| %>
  <%= f.input :name, placeholder: "Type name..." %>
  <%= f.input :overview, placeholder: "Overview..." %>
  <%= f.input :address, placeholder: "Address..." %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Add to my Venues", class: "btn bg-dark text-white" %>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-dropworks">
  <div class="navbar-icons">
    <%# Home %>
    <%= link_to root_path do %>
      <% if params[:controller] == "pages" && params[:action] == "home" %>
        <i class="bi-pin-map active-item"></i>
        <p class="active-item">Map</p>
      <% else %>
        <i class="bi-pin-map"></i>
        <p>Map</p>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-icons">
    <%# Search %>
    <%= link_to venues_path do %>
      <% if params[:controller] == "venues" && params[:action] == "index" %>
        <i class="bi-search active-item"></i>
        <p class="active-item">Search</p>
      <% else %>
        <i class="bi-search"></i>
        <p>Search</p>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-icons">
    <%# Check in %>
    <%= link_to read_path do %>
      <% if params[:controller] == "pages" && params[:action] == "read" %>
        <i class="bi-qr-code-scan active-item"></i>
        <p class="active-item">Check-in</p>
      <% else %>
        <i class="bi-qr-code-scan"></i>
        <p>Check-in</p>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-icons">
    <%# Activity %>
    <%= link_to activity_path do %>
      <% if params[:controller] == "pages" && params[:action] == "activity" %>
        <i class="bi-bell active-item"></i>
        <p class="active-item">Activity</p>
      <% else %>
        <i class="bi-bell"></i>
        <p>Activity</p>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-icons">
    <%# Profile %>
    <%= link_to dashboard_path do %>
      <% if params[:controller] == "pages" && params[:action] == "dashboard" %>
        <i class="bi-person active-item"></i>
        <p class="active-item">Profile</p>
      <% else %>
        <i class="bi-person"></i>
        <p>Profile</p>
      <% end %>
    <% end %>
  </div>
</div>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
        </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="search-bar-wrapper">
  <div class="form-inputs-sb">
    <%= form_with url: venues_path, method: :get, class: "simple-form-sb", data: { action: "keyup->search#update"} do |form| %>
      <%= text_field_tag :query,
          params[:query],
          class: "custom-input-class-sb",
          placeholder: "Search..."
      %>
    <% end %>
  </div>
</div>

app/views/shared/_table_bookings.html.erb
<table class="styled-table">
    <thead class="border-bottom p-2">
        <tr>
          <th>Venue</th>
          <th>Date</th>
          <th>Details</th>
        </tr>
    </thead>
    <tbody>
      <% user_bookings.sort_by { |b| [b.booking_date, b.venue.name] }.reverse.each do |b| %>
        <tr class="border-bottom p-2">
            <td><%= b.venue.name %></td>
            <td><%= b.booking_date %></td>
            <td>
              <%= link_to booking_path(b) do %>
                <i class='bi-search'></i> Details
              <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/shared/_table_review.html.erb
<table class="styled-table mt-4">
    <thead class="border-bottom p-2">
        <tr>
            <th>#id</th>
            <th>content</th>
            <th>rating</th>
        </tr>
    </thead>
    <tbody>
      <% user_venues.each do |v| %>
        <tr class="border-bottom p-2">
            <td><%= v.id %></td>
            <td><%= v.name %></td>
            <td><%= v.address %></td>
            <td><%= v.capacity %></td>
            <td>
              <%= link_to "Edit", edit_venue_path(v) %>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/shared/_table_reviews.html.erb
<table class="styled-table mt-4">
    <thead class="border-bottom p-2">
        <tr>
            <th>#id</th>
            <th>content</th>
            <th>rating</th>
        </tr>
    </thead>
    <tbody>
      <% user_venues.each do |v| %>
        <tr class="border-bottom p-2">
            <td><%= v.id %></td>
            <td><%= v.name %></td>
            <td><%= v.address %></td>
            <td><%= v.capacity %></td>
            <td>
              <%= link_to "Edit", edit_venue_path(v) %>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/shared/_table_venues.html.erb
<table class="styled-table mt-4">
    <thead class="border-bottom p-2">
        <tr>
            <th>#id</th>
            <th>Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
      <% user_venues.each do |v| %>
        <tr class="border-bottom p-2">

            <td><%= v.id %></td>
            <td><%= v.name %></td>
            <td><%= link_to "See Venue ➔", venue_path(v) %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/shared/_table_venues_bookings.html.erb
<table class="styled-table">
    <thead class="border-bottom p-2">
        <tr>
          <th>Venue</th>
          <th>Date</th>
          <th>Guest Name</th>
        </tr>
    </thead>
    <tbody>
      <% my_venues_booked.sort_by { |b| b.booking_date }.reverse.each do |b| %>
        <tr class="border-bottom p-2">
            <td><%= b.venue.name %></td>
            <td><%= b.booking_date %></td>
            <td><%= "#{b.user.first_name} #{b.user.last_name}" %></td>
        </tr>
      <% end %>
    </tbody>
</table>