config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :venues do
    member do
      patch :favorite
      get :confirm
      get :success
    end
    resources :bookings, only: %i[new create]


  end

  resources :bookings, only: %i[show edit update destroy] do
    resources :reviews,  only: %i[new create edit update]
  end

  get "read", to: "pages#read"
  get "/dashboard", to: "pages#dashboard"
  get "/activity", to: "pages#activity"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/venue.rb
class Venue < ApplicationRecord
  # database relationships
  belongs_to :user
  has_many_attached :photos
  # has_many :reviews, through: :bookings
  has_many :bookings, dependent: :destroy
  has_many  :favorites, dependent: :destroy
  has_many  :opening_hours, dependent: :destroy

  # input validations for new instances
  validates :name, presence: true
  validates :address, presence: true

  # mapbox scripts
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # pg_search scripts
  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
  against: [ :name, :address ],
  using: {
    tsearch: { prefix: true }
  }
  # If we wanna use current location in realm life we need to pass to distance_to 2 arguments (user_latitude, user_longtitude)
  def distance_to
    distance_km = Geocoder::Calculations.distance_between(
      [latitude, longitude],
      # Hardcoded IP Le Wagon address
      [52.50703626587969, 13.391801861290157]
    )
    # Convert distance to km if it more than 1 and round it to one decimal
    if distance_km >= 1
      return "#{distance_km.round(1)} km"
    else
      distance_m = distance_km * 1000
      return "#{distance_m.to_int} m"
    end
  end

  def average_rating
    ratings = []
    self.bookings.each do |booking|
      if booking.review
        ratings.push(booking.review.rating)
      end
    end

    return nil if ratings.empty?

    return (ratings.sum / ratings.length)
  end
  public :average_rating
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy favorite confirm success]

  def index
    # scrip 5-9 responsible for search bar feature
    if params[:query].present?
      @venues = Venue.search_by_name_and_address(params[:query])
    else
      @venues = Venue.all
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "venues/list", locals: {venues: @venues}, formats: [:html] }
    end
  end

  def show
    @booking = Booking.find_by(venue: @venue)
    @opening_hours = @venue.opening_hours
    # Get the current date and time
    now = Time.now

    # Get the day of the week (Sunday is 0 and Saturday is 6)
    current_day_index = now.wday

    # List of days
    days_of_week = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

    # Get the current day
    @current_day = days_of_week[current_day_index]

    # The logic to fetch and display the venue goes here
    @venue = Venue.find(params[:id])

    @current_user_booking = @venue.bookings.find_by(user: current_user)
    @has_reviewed = @current_user_booking&.review.present?
    # @is_venue_open = @current_day_opening_hour.present? && venue_open?(@current_day_opening_hour)
    # Find the current day
    current_day_name = Time.now.strftime('%A')

    # Find the venue's opening hours for the current day

    # @current_day_opening_hour = Venue.last.opening_hours.find_by(day: current_day_name)
      @today_check = @venue.opening_hours.select do |opening_hour|
        current_day_name == opening_hour.day.capitalize
      end.first
    @open =  Time.now.strftime('%H:%M') <= @today_check.closing_time.strftime('%H:%M') ? { text: "Open", color: "#359746" } : { text: "Closed", color: "#FF2D55" }
    # puts "Current Day: #{current_day_name}"
    # puts "Opening Hour: #{@current_day_opening_hour&.inspect}"
    # puts "Current Day: #{Time.now.strftime('%A')}"
    # puts "Opening Hour: #{@current_day_opening_hour&.inspect}"
    # puts "Is Venue Open? #{@is_venue_open}"
    url_to_pass_to_qr = confirm_venue_path(@venue)

    @qrcode = RQRCode::QRCode.new("#{request.base_url}/#{url_to_pass_to_qr}")
    @svg = @qrcode.as_svg

  end

  def new
    @venue = Venue.new
  end

  def confirm
  end

  def success
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user_id = current_user.id
    if @venue.save
      redirect_to venues_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @venue.update(venue_params)
      redirect_to venues_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @venue.destroy
    redirect_to venues_path
  end

  # member_route
  def favorite
    @favorite = Favorite.find_by(venue: @venue)
    if @favorite
      @favorite.update(liked: !@favorite.liked)
    else
      @favorite = Favorite.new
      @favorite.venue = @venue
      @favorite.user = current_user
      @favorite.liked = true
      @favorite.save!
    end
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :address, :overview, image_urls: [], photos: [])
  end

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def venue_open?(opening_hour)
    current_time = Time.now.strftime('%H:%M:%S')
    current_time.between?(opening_hour.open_time, opening_hour.closing_time)
  end
end

app/views/venues/_info_window.html.erb
<div class="map-card">
  <div class="d-flex" style="height: 100px; width: 100%;">
    <div class="venue-image" style="background-image: url('<%= venue.image_urls.first %>')">
      <%# <img src="<%= venue.image_urls.first %>
    </div>
    <div class="info-container">
      <div class="info-card">
        <%= link_to venue_path(venue.id) do %>
          <h4><%= venue.name %></h4>
          <p><%= venue.overview.truncate(40) %></p>
          <p>
            <% if venue.average_rating %>
            <% full_stars = venue.average_rating.to_i %>
                    <% full_stars.times do %>
                      <i class="bi bi-star-fill" style="color: #FF8500; font-size: 17px;"></i>
                    <% end %>

                    <% if venue.average_rating.to_s.split(".")[1].to_i > 2 && venue.average_rating.to_s.split(".")[1].to_i < 8 %>
                      <i class="bi bi-star-half" style="color: #FF8500; font-size: 17px;"></i>
                      <% empty_stars = 5 - full_stars - 1 %>
                    <% else %>
                      <% empty_stars = 5 - full_stars %>
                    <% end %>

                    <% (empty_stars).times do %>
                      <i class="bi bi-star" style="color: #FF8500; font-size: 17px;"></i>
                    <% end %>

                  <% else %>
                    <% 5.times do %>
                      <i class="bi bi-star" style="color: #D1D1D6; font-size: 17px;"></i>
                    <% end %>
                  <% end %>
          </p>
          <div class="info-window-icon-container">
            <div class="icon-info-pair">
              <i class="bi-person-add"></i>
              <p><%= venue.capacity %></p>
            </div>
            <div class="icon-info-pair">
              <i class="bi-wifi"></i>
              <p><%= venue.wifi_speed %> mbit/s</p>
            </div>
            <div class="icon-info-pair">
              <i class="bi-cursor"></i>
              <p><%= venue.distance_to %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/_list.html.erb
<% venues.each do |venue| %>
        <div class="venue-card" data-controller="favorite">
          <div class="favorite-heart">
            <% favorite = Favorite.find_by(venue: venue) %>
            <% if favorite && favorite.liked %>
              <%= link_to favorite_venue_path(venue, favorite: favorite), remote: true, data: { action: "click->favorite#favorite", turbo_method: :patch } do %>
                <i class="bi bi-bookmark-heart" data-favorite-target="heartIcon" style="color: #007AFF"></i>
              <% end %>
            <% else %>
              <%= link_to favorite_venue_path(venue, favorite: favorite), remote: true, data: { action: "click->favorite#favorite", turbo_method: :patch } do %>
                <i class="bi bi-bookmark-heart-fill" data-favorite-target="heartIcon" style="color: #007AFF"></i>
              <% end %>
            <% end %>
          </div>
          <%= link_to venue_path(venue.id) do %>
            <div class="image">

              <img class="img-properties-form" src="<%= venue.image_urls.first %>" alt="Venue-picture">
                <div>
                  <% if venue.photos.attached? %>
                    <div>
                      <% venue.photos.each do |photo| %>
                      <%= cl_image_tag photo.key %>
                      <% end %>
                    </div>
                  <% end %>
                </div>
            </div>

            <div class="info">
              <div class="mt-2">
                <h6 style="width:47%; margin-bottom: 0"><%= venue.name %></h6>
                <p style="width:31%;">
                  <% if venue.average_rating %>
                    <% full_stars = venue.average_rating.to_i %>
                    <% full_stars.times do %>
                      <i class="bi bi-star-fill" style="color: #FF8500; font-size: 17px;"></i>
                    <% end %>

                    <% if venue.average_rating.to_s.split(".")[1].to_i > 2 && venue.average_rating.to_s.split(".")[1].to_i < 8 %>
                      <i class="bi bi-star-half" style="color: #FF8500; font-size: 17px;"></i>
                      <% empty_stars = 5 - full_stars - 1 %>
                    <% else %>
                      <% empty_stars = 5 - full_stars %>
                    <% end %>

                    <% (empty_stars).times do %>
                      <i class="bi bi-star" style="color: #FF8500; font-size: 17px;"></i>
                    <% end %>

                  <% else %>
                    <% 5.times do %>
                      <i class="bi bi-star" style="color: #D1D1D6; font-size: 17px;"></i>
                    <% end %>
                  <% end %>
                </p>
                <p style="width:22%; text-align: right" class="card-wifi-speed"><i class="bi-wifi"></i> <%= venue.wifi_speed %> mbit/s</p>
              </div>

              <div>
                <p style="width:47%; padding-right: 8px;" class="card-overview-text"><%= venue.overview %></p>
                <p style="width:33%;" class="seat-available" ><i class="bi-person-add"></i> <span style="color: #359746; margin: 0 4px"> <%= venue.capacity %> </span> seats available</p>
                <p style="width:20%; text-align: right" class="card-distance"><i class="bi-cursor"></i> <%= venue.distance_to %></p>
              </div>
            </div>
          <% end %>

        </div>
      <% end %>

app/views/venues/_marker.html.erb
<%# <div class="badge rounded-pill bg-primary fs-6"> %>
  <%#= venue.name %>
<%# </div> %>

app/views/venues/confirm.html.erb
<div class="confirm">
  <% if @venue.present? %>
      <img src="https://i.ibb.co/vVh0R2W/ms-icon-310x310.png" class="dropworks-logo" alt="DropWorks Logo">
      <h3>Do you want to check-in to</h3>
      <h1><%= @venue.name %>?</h1>
      <br>
      <%= @venue.address %>
      <br>
      <div class="button-container">
        <%= link_to root_path, class: "btn btn-secondary" do %>
          <i class="bi-x-circle"></i> Cancel
        <% end %>
        <%= link_to success_venue_path(@venue), class: "btn btn-primary" do %>
          <i class="bi-check-lg"></i> Check in
        <% end %>
      </div>
  <% else %>
    <p>Venue not found... <br>Why don't you open a DropWorks venue yourself? 😇</p>
  <% end %>
</div>

app/views/venues/create.html.erb
<h1>Venues#create</h1>
<p>Find me in app/views/venues/create.html.erb</p>

app/views/venues/destroy.html.erb
<h1>Venues#destroy</h1>
<p>Find me in app/views/venues/destroy.html.erb</p>

app/views/venues/edit.html.erb
<h1>Venues#edit</h1>
<p>Find me in app/views/venues/edit.html.erb</p>

<%= render "shared/form_venue", venue: @venue %>

app/views/venues/index.html.erb
<div data-controller="search">
  <%# search bar component - begin of script -BL %>
    <%= render "shared/search_bar" %>
  <%# grid system to display venues %>
  <h1> Spaces close to you...</h1>
  <div class="row" data-search-target="results" style="padding-bottom: 100px" data-search-target="cards">
    <%= render "list", venues: @venues %>
  </div>
</div>

app/views/venues/new.html.erb
<h1>Venues#new</h1>
<p>Find me in app/views/venues/new.html.erb</p>

<%= render "shared/form_venue", venue: @venue %>

app/views/venues/show.html.erb
<div class="show-page-container container">
  <div class="container">
    <div class="container image-container">
      <div class="splide" data-controller="splide">
        <div class="splide__track">
          <!-- Additional required wrapper -->
          <ul class="splide__list">
            <% if @venue.photos.attached? %>
              <% @venue.photos.each do |photo| %>
                <li class="splide__slide">
                  <%= cl_image_tag photo.key, class: "w-100 h-100"%>
                </li>
              <% end %>
            <% else %>
              <% @venue.image_urls.each do |venue_image| %>
                <li class="splide__slide">
                  <img class="image-carousel" src="<%= venue_image %>">
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-venue">
  <div class="container-title-description">
    <h1 style="margin-bottom: 0px; margin-top: 18px;"><%= @venue.name %></h1>
    <p>
      <% if @venue.average_rating %>
      <%= @venue.average_rating.round(1) %>
        <% full_stars = @venue.average_rating.to_i %>
        <% full_stars.times do %>
          <i class="bi bi-star-fill" style="color: #FF8500; font-size: 17px;"></i>
        <% end %>

       <% if @venue.average_rating.to_s.split(".")[1].to_i > 2 && @venue.average_rating.to_s.split(".")[1].to_i < 8 %>
          <i class="bi bi-star-half" style="color: #FF8500; font-size: 17px;"></i>
          <% empty_stars = 5 - full_stars - 1 %>
        <% else %>
          <% empty_stars = 5 - full_stars %>
        <% end %>

          <% (empty_stars).times do %>
            <i class="bi bi-star" style="color: #FF8500; font-size: 17px;"></i>
          <% end %>

          <% else %>
             <% 5.times do %>
               <i class="bi bi-star" style="color: #D1D1D6; font-size: 17px;"></i>
            <% end %>
          <% end %>
           <span style="color: #48484A; font-weight: 400;">(<%= @venue.bookings.joins(:review).distinct.size.to_s %>)</span>
    </p>
    <div class="block-text-overview">
      <p><%= @venue.overview %></p>
    </div>
  </div>

  <div class="show-page-buttons-container">

    <div class="icon-text-button-pair">
      <div class="circle-icon-container">
        <%= link_to "https://maps.google.de/?q=#{@venue.name}+#{@venue.address}" do %>
          <i class="bi-cursor"></i>
        <% end %>
      </div>
      <%= link_to "https://maps.google.de/?q=#{@venue.name}+#{@venue.address}" do %>
        <p>Navigate</p>
      <% end %>
    </div>

    <div class="icon-text-button-pair" data-controller="favorite">
      <%= turbo_frame_tag 'favorite_frame' do %>
        <% favorite = Favorite.find_by(venue_id: @venue) %>
        <% unless favorite && favorite.liked %>
          <%= link_to favorite_venue_path(@venue, favorite: favorite), remote: true, data: { turbo_frame: "favorite_frame", action: "click->favorite#favorite", turbo_method: :patch } do %>
            <div class="circle-icon-container">
              <i class="bi-bookmark-heart-fill" data-favorite-target="heartIcon"></i>
            </div>
            <p data-favorite-target="saveText">Saved</p>
          <% end %>
        <% else %>
          <%= link_to favorite_venue_path(@venue, favorite: favorite), remote: true, data: { turbo_frame: "favorite_frame", action: "click->favorite#favorite", turbo_method: :patch } do %>
            <div class="circle-icon-container">
              <i class="bi-bookmark-heart" data-favorite-target="heartIcon"></i>
            </div>
            <p data-favorite-target="saveText">Save</p>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="<%= (!@current_user_booking.present? || @has_reviewed)? 'icon-text-button-pair-disabled' : 'icon-text-button-pair-primary' %>"
      data-controller="disable-review" data-review-button-target="reviewButton" data-disable-review-enabled="false">

      <div class="circle-icon-container">
        <% if @current_user_booking.present? && !@has_reviewed %>
          <%= link_to new_booking_review_path(@current_user_booking), data: { turbo_frame: "review_frame" } do %>
            <i class="bi bi-chat-square-text"></i>
          <% end %>
        <% else %>
          <i class="bi bi-chat-square-text"></i>
        <% end %>
      </div>
      <p style="text-align: center">Review</p>
    </div>

    <div class="icon-text-button-pair-primary">
      <div class="circle-icon-container">
        <%= link_to new_venue_booking_path(@venue) do %>
          <i class="bi-calendar-plus"></i>
        <% end %>
      </div>
      <%= link_to new_venue_booking_path(@venue) do %>
        <p>Reserve</p>
      <% end %>
    </div>

  </div>

  <div class="live-info">
    <div class="info-column">
      <div class="live-info-icon-text-pair">
        <i class="bi-clock"></i>
        <div class="open-hour-text">
          <p> <span style="margin-right: 4px; font-weight: 700; color: <%= @open[:color] %>"><%= @open[:text] %></span>
          <% if @today_check.present? %>
            <% if @today_check.open_time.present? %>
              <p>• Closes at <%= @today_check.closing_time.strftime('%H:%M') %></p>
            <% else %>
              <p>• Opens at <%= @today_check.open_time.strftime('%H:%M') %></p>
            <% end %>
          <% else %>
            <p>Opening hours unavailable</p>
          <% end %>
          </p>
        </div>
      </div>
      <div class="live-info-icon-text-pair">
        <i class="bi-question-circle"></i>
        <p>Never visited<p>
      </div>
    </div>
    <div class="info-column">
      <div class="live-info-icon-text-pair">
        <i class="bi-people"></i>
        <p><%= @venue.capacity %> seats available<p>
      </div>
      <div class="live-info-icon-text-pair">
        <i class="bi-wifi"></i>
        <p><%= @venue.wifi_speed %> mbit/s<p>
      </div>
    </div>
  </div>

  <div class="static-info-container">
    <h3>Opening Hours</h3>
    <div class="day-dropdown" data-controller="day-selector">
      <button class="dropdown-button" type="button" data-action="click->day-selector#toggleDropdown">
        <p>Today: <%= @current_day %><span style="font-size: 16px; color: #007AFF"> ↧</span></p>
      </button>
      <ul class="day-list closed"  data-day-selector-target="dropdown">
        <% @opening_hours.each do |opening_hour| %>
        <%# Giorgios Code following: - FS %>
          <li><%= "#{opening_hour.day.capitalize}s from #{opening_hour.open_time.strftime('%H:%M')} to #{opening_hour.closing_time.strftime('%H:%M')}" %></li>
        <%# Giorgios Code end - FS %>
        <% end %>
      </ul>
    </div>
    <h3>Address</h3>
    <p><%= @venue.address %></p>
    <p><%= link_to "See address on Google Maps ", "https://maps.google.de/?q=#{@venue.name}+#{@venue.address}" %><i class="bi-box-arrow-up-right"></i></p>
  </div>

  <div class="reviews-block">
    <%# Found this much more elegant way to implement the h2 and the plus button: -FS %>
    <h2>
      Reviews
      <span style="color: #48484A; font-weight: 400;">(<%= @venue.bookings.joins(:review).distinct.size.to_s %>)</span>
      <% if @current_user_booking.present? && !@has_reviewed %>
        <%= link_to new_booking_review_path(@current_user_booking), data: { turbo_frame: "review_frame" } do %>
          <i class="bi-plus-circle-fill"></i>
        <% end %>
      <% else %>
        <i class="bi-plus-circle-fill" style="color: #D1D1D6"></i>
      <% end %>
    </h2>
    <div class="review-list">
      <% @venue.bookings.each do |booking| %>
        <% if !booking.review.nil? %>
          <div class="review-wrapper">
            <p class="review-user-name">
              <%= booking.review.user.first_name %>
              <%= booking.review.user.last_name %>
              <i class="bi-star-fill" style="style: font-size: 8px; color: #FF8500"></i>
              <span style="font-weight: 300;">
                <%= booking.review.rating.to_i %>
              </span>
            </p>
            <p><%= booking.review.content %></p>
            <% if booking.review.photos.attached? %>
              <% booking.review.photos.each do |photo| %>
                <%= link_to "#", id: "imageModalTrigger", data: { controller: "modal-trigger", action:"click->modal-trigger#open"} do %>
                  <%= cl_image_tag photo.key, class: "review-images-small"%>
                <% end %>
                <div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <%=  cl_image_tag photo.key, class: "review-images-big"  %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <!-- Additional buttons or content can be added here -->
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="floating-reserve-button">
    <%= link_to new_venue_booking_path(@venue) do %>
      <div class="circle-container-white">
        <i class="bi bi-calendar-plus"></i>
      </div>
    <% end %>
    <p>Reserve</p>
  </div>
    <div class="d-none"><%=  @svg.html_safe  %></div>
</div>

app/views/venues/success.html.erb
<div class="blurry-background">
  <img class="img-properties-form" src="<%= @venue.image_urls.first %>" alt="Venue-picture">
</div>
<div>
  <div class="success-container">
    <div class="icon-style">
      <i class="bi bi-check-lg"></i>
    </div>
    <h1>Success</h1>
    <h3> Thank you for check-in. <br>Please ask the staff for ☕️ and 🫖!</h3>
    <div class="success-button">
      <%= link_to "See my Bookings", activity_path %>
    </div>
  </div>
</div>

app/views/venues/update.html.erb
<h1>Venues#update</h1>
<p>Find me in app/views/venues/update.html.erb</p>